# Generated by Django 2.1.11 on 2019-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicIscritto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('data_di_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
