# Generated by Django 2.1.11 on 2019-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IscrittoBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('data_di_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(default='', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
