# Generated by Django 2.1.11 on 2019-08-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0002_iscrittobase'),
    ]

    operations = [
        migrations.CreateModel(
            name='IscrittoKarate',
            fields=[
                ('iscrittobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iscrizioni.IscrittoBase')),
                ('note', models.TextField(max_length=100)),
            ],
            bases=('iscrizioni.iscrittobase',),
        ),
        migrations.DeleteModel(
            name='BasicIscritto',
        ),
        migrations.AddField(
            model_name='iscrittobase',
            name='certificato_medico',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
