# Generated by Django 2.1.11 on 2019-08-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0003_auto_20190821_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=4)),
                ('certificato_medico', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('data_di_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(default='', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='iscrittokarate',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscrizioni.Persona'),
        ),
    ]
