# Generated by Django 2.1.11 on 2019-08-24 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iscrizioni', '0004_auto_20190824_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name': 'Iscrizione', 'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Iscritto', 'verbose_name_plural': 'Iscritti'},
        ),
        migrations.RenameField(
            model_name='iscrizione',
            old_name='anno',
            new_name='anno_iscrizione',
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='data_iscrizione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
